version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - toshimaru
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: font-awesome-sass
    versions:
    - "< 6, >= 5.0.a"
  - dependency-name: rubocop-performance
    versions:
    - 1.11.0
    - 1.11.1
    - 1.11.3
  - dependency-name: rubocop-rails
    versions:
    - 2.10.1
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.13.0
    - 1.14.0
  - dependency-name: rails
    versions:
    - 6.1.2.1
    - 6.1.3
    - 6.1.3.1
  - dependency-name: rubocop-ast
    versions:
    - 1.4.2
  - dependency-name: parser
    versions:
    - 3.0.1.0
    - 3.0.1.1
  - dependency-name: mini_portile2
    versions:
    - 2.5.1
  - dependency-name: webpacker
    versions:
    - 5.2.2
  - dependency-name: rexml
    versions:
    - 3.2.5
  - dependency-name: mimemagic
    versions:
    - 0.3.6
    - 0.3.7
    - 0.3.8
  - dependency-name: rspec-rails
    versions:
    - 4.1.1
    - 5.0.1
  - dependency-name: nio4r
    versions:
    - 2.5.6
  - dependency-name: uniform_notifier
    versions:
    - 1.14.0
  - dependency-name: minitest
    versions:
    - 5.14.4
  - dependency-name: regexp_parser
    versions:
    - 2.1.0
    - 2.1.1
  - dependency-name: rubocop-rails_config
    versions:
    - 1.4.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
